export interface TyporaPreferences {
    'NSWindow Frame NSSpellCheckerSubstitutionsPanel2': string;
    WebKitDeveloperExtras: boolean;
    schemeAwareness: boolean;
    'NSWindow Frame NSNavPanelAutosaveName': string;
    SUHasLaunchedBefore: boolean;
    darkTheme: string;
    preLinebreakOnExport: boolean;
    NSNavLastRootDirectory: string;
    noHintForOpenLink: boolean;
    license: string;
    'NSWindow Frame _ClosedWindowFrame': string;
    enable_inline_math: boolean;
    hasThemeFolder: boolean;
    SUEnableAutomaticChecks: boolean;
    currentThemeFolder: string;
    NSNavPanelExpandedSizeForOpenMode: string;
    WKWebView_ver: string;
    uuid: string;
    copy_markdown_by_default: boolean;
    theme: string;
    backgroundColor: string;
    useDarkTheme: boolean;
    NSNavPanelExpandedSizeForSaveMode: string;
    initialize_ver: string;
    SULastCheckTime: Date;
    send_usage_info: boolean;
    email: string;
    verInitTime: Date;
    use_seamless_window: boolean;
    NSNavPanelExpandedStateForSaveMode: boolean;
    recentFolder: string[];
    useTreeStyle: boolean;
    backgroundColor2: number[];
    pinFolder: string;
    sidebar_tab: string;
    'Release Group': string;
    strict_mode: boolean;
}